### ISSUE TITLE
Missing requirements?

### ISSUE THREAD

**Issue by max-rocket-internet** [anchore/anchore-cli#20]
```
$ pip install --user anchorecli
Collecting anchorecli
Requirement already satisfied: requests in ./Library/Python/3.6/lib/python/site-packages (from anchorecli) (2.19.1)
Requirement already satisfied: click in /usr/local/lib/python3.6/site-packages (from anchorecli) (6.7)
Requirement already satisfied: PyYAML in ./Library/Python/3.6/lib/python/site-packages (from anchorecli) (3.13)
Requirement already satisfied: python-dateutil in ./Library/Python/3.6/lib/python/site-packages (from anchorecli) (2.7.3)
Requirement already satisfied: urllib3 in ./Library/Python/3.6/lib/python/site-packages (from anchorecli) (1.23)
Collecting prettytable (from anchorecli)
Requirement already satisfied: certifi>=2017.4.17 in ./Library/Python/3.6/lib/python/site-packages (from requests->anchorecli) (2018.8.13)
Requirement already satisfied: idna<2.8,>=2.5 in ./Library/Python/3.6/lib/python/site-packages (from requests->anchorecli) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->anchorecli) (3.0.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil->anchorecli) (1.11.0)
Installing collected packages: prettytable, anchorecli
  The script anchore-cli is installed in '/Users/max.williams/Library/Python/3.6/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed anchorecli-0.2.4 prettytable-0.7.2
```

```
$ anchore-cli system status
Traceback (most recent call last):
  File "/Users/max.williams/Library/Python/3.6/bin/anchore-cli", line 7, in <module>
    from anchorecli.cli import main_entry
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/anchorecli/cli/__init__.py", line 7, in <module>
    import image, policy, evaluate, subscription, registry, system, utils, repo, event
ModuleNotFoundError: No module named 'image'
```

```
$ pip install --user image
Collecting image
  Downloading https://files.pythonhosted.org/packages/a7/5b/c0358fe83daab29070e38a945809585f1fd6353e65b687f602688f32c3c2/image-1.5.24-py2.py3-none-any.whl
Requirement already satisfied: pillow in ./Library/Python/3.6/lib/python/site-packages (from image) (5.2.0)
Collecting django (from image)
  Downloading https://files.pythonhosted.org/packages/ca/7e/fc068d164b32552ae3a8f8d5d0280c083f2e8d553e71ecacc21927564561/Django-2.1.1-py3-none-any.whl (7.3MB)
    100% |████████████████████████████████| 7.3MB 1.9MB/s
Requirement already satisfied: pytz in ./Library/Python/3.6/lib/python/site-packages (from django->image) (2018.5)
Installing collected packages: django, image
  The script django-admin is installed in '/Users/max.williams/Library/Python/3.6/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed django-2.1.1 image-1.5.24
```

```
$ anchore-cli system status
Traceback (most recent call last):
  File "/Users/max.williams/Library/Python/3.6/bin/anchore-cli", line 7, in <module>
    from anchorecli.cli import main_entry
  File "/Users/max.williams/Library/Python/3.6/lib/python/site-packages/anchorecli/cli/__init__.py", line 7, in <module>
    import image, policy, evaluate, subscription, registry, system, utils, repo, event
ModuleNotFoundError: No module named 'policy'
```

etc

**Comment by zhill** [comment]
Hi @max-rocket-internet , it looks like you're installing with py3, the cli only currently supports py2.7. We're working on adding py3 support and it is merged into the master branch, but we have not yet released the py3 version yet so using pip you're getting the py2 only version. The module imports are a little different from 2->3 and that's what you're seeing in those errors.

We also have a [container:](https://hub.docker.com/r/anchore/engine-cli/) if you don't want to mess with py2 of virtual envs.

**Comment by max-rocket-internet** [comment]
Ahh OK. All good, thanks for the reply.
